export const EXPENSE_CATEGORIES = [
  "Groceries",
  "Restaurants",
  "Rent",
  "Utilities",
  "Bills",
  "Transport",
  "Fuel",
  "Shopping",
  "Personal",
  "Healthcare",
  "Insurance",
  "Entertainment",
  "Travel",
  "Subscriptions",
  "Education",
  "Fees",
  "Taxes",
  "Gifts/Donations",
  "Pets",
  "Childcare",
  "Fitness",
  "Home Improvement",
  "Cash Withdrawal",
  "Business",
  "Other",
];
